export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  RESET_PRODUCTS: "RESET_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
